/**
 * Vanilla tRPC Client - Imperative tRPC calls for Zustand stores
 * ipclink-singleton-unification: Task 1.1
 * Requirements: 1.1, 1.2, 1.3, 1.4
 *
 * Provides a tRPC proxy client that can be used outside React components
 * (e.g., in Zustand stores) for imperative procedure calls.
 *
 * The proxy is created from the shared TRPCClient instance generated by
 * provider.tsx via setSharedClient(). This ensures a single ipcLink() call
 * and eliminates requestId collisions (electron-trpc Issue #201).
 *
 * Before setSharedClient() is called (i.e., before React mount), it now
 * attempts to create a standalone IPC client if in a browser environment.
 * If that fails, it returns a deferred proxy that queues subscribe operations.
 */
import { createTRPCClientProxy } from '@trpc/client';
import { createTRPCClient, type TRPCClient, type CreateTRPCProxyClient } from '@trpc/client';
import { ipcLink } from 'electron-trpc/renderer';
import type { AppRouter } from '../../main/trpc/router';

type VanillaClient = CreateTRPCProxyClient<AppRouter>;

/** Queued subscribe operation for deferred replay */
interface DeferredSubscription {
  path: string[];
  args: unknown[];
}

let vanillaClient: VanillaClient | null = null;
let deferredSubscriptions: DeferredSubscription[] = [];
let deferredProxy: VanillaClient | null = null;

/**
 * Check if electron-trpc bridge is available in window
 */
function getTRPCBridge(): any {
  if (typeof window === 'undefined') return null;
  return (window as any).electronTRPC || (window as any).__electronTRPC__;
}

/**
 * Create a deferred proxy that queues subscribe calls and throws on query/mutate.
 * This is used when getVanillaClient() is called before setSharedClient() and IPC is not available.
 */
function createDeferredProxy(): VanillaClient {
  const createNestedProxy = (path: string[]): unknown => {
    return new Proxy(() => {}, {
      get: (_target, prop) => {
        if (typeof prop !== 'string') return undefined;
        // Avoid intercepting Promise-like properties
        if (prop === 'then' || prop === 'catch' || prop === 'finally') return undefined;
        return createNestedProxy([...path, prop]);
      },
      apply: (_target, _thisArg, args) => {
        const lastSegment = path[path.length - 1];

        // Check again if bridge became available in the meantime
        if (!vanillaClient) {
          const bridge = getTRPCBridge();
          if (bridge) {
            console.info('[vanillaClient] Bridge found during proxy call, creating client');
            const client = createTRPCClient<AppRouter>({
              links: [ipcLink()],
            });
            vanillaClient = createTRPCClientProxy<AppRouter>(client);
          }
        }

        // If we have a real client now, use it
        if (vanillaClient) {
          let target: any = vanillaClient;
          for (const segment of path) {
            target = target[segment];
          }
          return target(...args);
        }

        if (lastSegment === 'subscribe') {
          // Queue the subscribe call for later replay
          deferredSubscriptions.push({ path: [...path], args });
          // Return a dummy unsubscribe handle
          return { unsubscribe: () => {} };
        }

        if (lastSegment === 'query' || lastSegment === 'mutate') {
          console.error(`[vanillaClient] ERROR: Cannot call ${path.join('.')}() before setSharedClient() and IPC link not available.`);
          throw new Error(
            `[vanillaClient] Cannot call ${path.join('.')}() before setSharedClient(). ` +
            `query/mutate are only available after TRPCProvider mounts.`
          );
        }

        // For other calls, also throw
        throw new Error(
          `[vanillaClient] Cannot call ${path.join('.')}() before setSharedClient().`
        );
      },
    });
  };

  return createNestedProxy([]) as VanillaClient;
}

/**
 * Flush deferred subscriptions by replaying them on the real proxy.
 */
function flushDeferredSubscriptions(): void {
  const pending = deferredSubscriptions;
  deferredSubscriptions = [];

  for (const { path, args } of pending) {
    // Navigate the real proxy to the subscribe method
    let target: any = vanillaClient;
    // path is like ['events', 'onAgentStartError', 'subscribe']
    for (const segment of path.slice(0, -1)) {
      target = target[segment];
    }
    // Call the subscribe method
    target.subscribe(...args);
  }
}

/**
 * Set the shared TRPCClient from provider.tsx.
 * Creates the vanilla proxy and flushes any deferred subscriptions.
 */
export function setSharedClient(client: TRPCClient<AppRouter>): void {
  console.info('[vanillaClient] Shared client set from TRPCProvider');
  vanillaClient = createTRPCClientProxy<AppRouter>(client);
  deferredProxy = null;

  // Flush any queued subscriptions
  flushDeferredSubscriptions();
}

/**
 * Get the singleton vanilla tRPC client.
 * In E2E/Production environment, if shared client is not yet set,
 * creates a standalone client using ipcLink to allow early calls.
 */
export function getVanillaClient(): VanillaClient {
  if (vanillaClient) {
    return vanillaClient;
  }

  // If in a browser-like environment with IPC availability,
  // we can create a standalone client immediately.
  const bridge = getTRPCBridge();
  if (bridge) {
    console.info('[vanillaClient] Creating early standalone IPC client');
    try {
      const client = createTRPCClient<AppRouter>({
        links: [ipcLink()],
      });
      vanillaClient = createTRPCClientProxy<AppRouter>(client);
      return vanillaClient;
    } catch (error) {
      console.error('[vanillaClient] Failed to create standalone IPC client:', error);
    }
  } else if (typeof window !== 'undefined') {
    console.warn('[vanillaClient] Browser environment detected but bridge (electronTRPC/__electronTRPC__) missing. Bridge not yet established?');
  }

  // Return deferred proxy (singleton)
  if (!deferredProxy) {
    console.info('[vanillaClient] Using deferred proxy');
    deferredProxy = createDeferredProxy();
  }
  return deferredProxy;
}

/**
 * Reset the singleton (for testing only).
 */
export function resetVanillaClient(): void {
  vanillaClient = null;
  deferredSubscriptions = [];
  deferredProxy = null;
}