/**
 * Vanilla tRPC Client - Imperative tRPC calls for Zustand stores
 * ipclink-singleton-unification: Task 1.1
 * Requirements: 1.1, 1.2, 1.3, 1.4
 *
 * Provides a tRPC proxy client that can be used outside React components
 * (e.g., in Zustand stores) for imperative procedure calls.
 *
 * The proxy is created from the shared TRPCClient instance generated by
 * provider.tsx via setSharedClient(). This ensures a single ipcLink() call
 * and eliminates requestId collisions (electron-trpc Issue #201).
 *
 * IMPORTANT: ipcLink() must ONLY be called in provider.tsx (SOLE location).
 * Before setSharedClient() is called (i.e., before TRPCProvider mounts),
 * getVanillaClient() returns a deferred proxy that queues subscribe operations.
 * query/mutate calls before setSharedClient() will throw.
 */
import { createTRPCClientProxy } from '@trpc/client';
import type { TRPCClient, CreateTRPCProxyClient } from '@trpc/client';
import type { AppRouter } from '../../main/trpc/router';

type VanillaClient = CreateTRPCProxyClient<AppRouter>;

/** Queued subscribe operation for deferred replay */
interface DeferredSubscription {
  path: string[];
  args: unknown[];
}

let vanillaClient: VanillaClient | null = null;
let deferredSubscriptions: DeferredSubscription[] = [];
let deferredProxy: VanillaClient | null = null;

/**
 * Create a deferred proxy that queues subscribe calls and throws on query/mutate.
 * This is used when getVanillaClient() is called before setSharedClient().
 * subscribe calls are queued and replayed when the real client is set.
 */
function createDeferredProxy(): VanillaClient {
  const createNestedProxy = (path: string[]): unknown => {
    return new Proxy(() => {}, {
      get: (_target, prop) => {
        if (typeof prop !== 'string') return undefined;
        // Avoid intercepting Promise-like properties
        if (prop === 'then' || prop === 'catch' || prop === 'finally') return undefined;
        return createNestedProxy([...path, prop]);
      },
      apply: (_target, _thisArg, args) => {
        const lastSegment = path[path.length - 1];

        // If real client became available (setSharedClient was called), delegate to it
        if (vanillaClient) {
          let target: any = vanillaClient;
          for (const segment of path) {
            target = target[segment];
          }
          return target(...args);
        }

        if (lastSegment === 'subscribe') {
          // Queue the subscribe call for later replay
          deferredSubscriptions.push({ path: [...path], args });
          // Return a dummy unsubscribe handle
          return { unsubscribe: () => {} };
        }

        if (lastSegment === 'query' || lastSegment === 'mutate') {
          console.error(`[vanillaClient] ERROR: Cannot call ${path.join('.')}() before setSharedClient() - TRPCProvider not yet mounted.`);
          throw new Error(
            `[vanillaClient] Cannot call ${path.join('.')}() before setSharedClient(). ` +
            `query/mutate are only available after TRPCProvider mounts.`
          );
        }

        // For other calls, also throw
        throw new Error(
          `[vanillaClient] Cannot call ${path.join('.')}() before setSharedClient().`
        );
      },
    });
  };

  return createNestedProxy([]) as VanillaClient;
}

/**
 * Flush deferred subscriptions by replaying them on the real proxy.
 */
function flushDeferredSubscriptions(): void {
  const pending = deferredSubscriptions;
  deferredSubscriptions = [];

  if (pending.length > 0) {
    console.info(`[vanillaClient] Flushing ${pending.length} deferred subscription(s)`);
  }

  for (const { path, args } of pending) {
    // Navigate the real proxy to the subscribe method
    let target: any = vanillaClient;
    // path is like ['events', 'onAgentStartError', 'subscribe']
    for (const segment of path.slice(0, -1)) {
      target = target[segment];
    }
    // Call the subscribe method
    target.subscribe(...args);
  }
}

/**
 * Set the shared TRPCClient from provider.tsx.
 * Creates the vanilla proxy and flushes any deferred subscriptions.
 * This must be called exactly once from TRPCProvider.
 */
export function setSharedClient(client: TRPCClient<AppRouter>): void {
  if (vanillaClient) {
    // Already initialized - skip to prevent multiple ipcLink instances
    // This can happen if React StrictMode double-invokes the initializer
    console.warn('[vanillaClient] setSharedClient called but client already set, ignoring');
    return;
  }
  console.info('[vanillaClient] Shared client set from TRPCProvider');
  vanillaClient = createTRPCClientProxy<AppRouter>(client);
  deferredProxy = null;

  // Flush any queued subscriptions
  flushDeferredSubscriptions();
}

/**
 * Get the singleton vanilla tRPC client.
 * Returns the real client if setSharedClient() has been called (after TRPCProvider mount),
 * otherwise returns a deferred proxy that queues subscribe calls.
 *
 * IMPORTANT: ipcLink() is NOT created here. All IPC connections are managed
 * exclusively by provider.tsx to prevent requestId collisions (electron-trpc Issue #201).
 */
export function getVanillaClient(): VanillaClient {
  if (vanillaClient) {
    return vanillaClient;
  }

  // Return deferred proxy (singleton)
  // subscribe calls are queued and replayed when setSharedClient() is called
  if (!deferredProxy) {
    console.info('[vanillaClient] Using deferred proxy (TRPCProvider not yet mounted)');
    deferredProxy = createDeferredProxy();
  }
  return deferredProxy;
}

/**
 * Reset the singleton (for testing only).
 */
export function resetVanillaClient(): void {
  vanillaClient = null;
  deferredSubscriptions = [];
  deferredProxy = null;
}
