/**
 * CreateBugDialog Component
 * Dialog for creating new bug reports via /kiro:bug-create
 * Requirements: 4.1, 4.2, 4.3, 4.4, 4.5, 4.6
 * bug-create-dialog-unification: Worktree mode switch and unified button styling
 */

import { useState } from 'react';
import { X, Loader2, AlertCircle, Bug, GitBranch } from 'lucide-react';
import { useProjectStore, useAgentStore, notify } from '../stores';
import { useBugStore } from '../stores/bugStore';
import { clsx } from 'clsx';
// bug-create-dialog-unification: AgentIcon/AgentBranchIcon for button icons
import { AgentIcon, AgentBranchIcon } from '../../shared/components/ui/AgentIcon';
// submit-shortcut-key: Task 2.3 - Keyboard shortcut hook
import { useSubmitShortcut } from '@shared/hooks';

interface CreateBugDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

/**
 * CreateBugDialog - Dialog for creating new bug reports
 * - Bug description textarea (required)
 * - Worktree mode switch (bug-create-dialog-unification)
 * - Create/Cancel buttons with unified styling
 * - Loading state during creation
 * - Bug name is auto-generated by Claude from description
 */
export function CreateBugDialog({ isOpen, onClose }: CreateBugDialogProps): React.ReactElement | null {
  const { currentProject } = useProjectStore();
  const { selectForProjectAgents, selectAgent, addAgent } = useAgentStore();
  const { refreshBugs } = useBugStore();

  const [description, setDescription] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  // bug-create-dialog-unification: Worktree mode state
  const [useWorktree, setUseWorktree] = useState(false);

  const handleDescriptionChange = (value: string) => {
    setDescription(value);
    setError(null);
  };

  const handleCreate = async () => {
    if (!currentProject) return;

    // Validate description
    const trimmedDescription = description.trim();
    if (!trimmedDescription) {
      setError('バグの説明を入力してください');
      return;
    }

    setIsCreating(true);
    setError(null);

    try {
      // Call bug-create via IPC (uses /kiro:bug-create)
      // Bug name is auto-generated by Claude from description per bug-create.md spec
      // bug-create-dialog-unification: Pass worktreeMode parameter
      const agentInfo = await window.electronAPI.executeBugCreate(currentProject, trimmedDescription, useWorktree);

      // Add agent to store and switch to project agents panel
      addAgent('', agentInfo);
      selectForProjectAgents();
      selectAgent(agentInfo.agentId);

      notify.success('バグレポート作成を開始しました（プロジェクトAgentパネルで進捗を確認できます）');

      // Refresh bugs list after a short delay to allow file creation
      setTimeout(() => refreshBugs(), 2000);

      handleClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'バグレポートの作成に失敗しました');
      setIsCreating(false);
    }
  };

  const handleClose = () => {
    setDescription('');
    setError(null);
    setIsCreating(false);
    onClose();
  };

  // Validation: description is required
  const isValid = description.trim().length > 0;

  // submit-shortcut-key: Task 2.3 - Keyboard shortcut for form submission
  // Note: Hook must be called before early return to comply with React rules of hooks
  const { handleKeyDown } = useSubmitShortcut({
    onSubmit: handleCreate,
    disabled: isCreating || !isValid,
  });

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center" data-testid="create-bug-dialog">
      {/* Backdrop */}
      <div
        className="absolute inset-0 bg-black/50"
        onClick={handleClose}
        data-testid="dialog-backdrop"
      />

      {/* Dialog */}
      {/* bug-create-dialog-unification: Changed from max-w-md to max-w-xl */}
      <div
        className={clsx(
          'relative z-10 w-full max-w-xl p-6 rounded-lg shadow-xl',
          'bg-white dark:bg-gray-900'
        )}
        data-testid="dialog-content"
      >
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <Bug className="w-5 h-5 text-red-500" />
            <h2 className="text-xl font-bold text-gray-800 dark:text-gray-200">
              新規バグレポート
            </h2>
          </div>
          <button
            onClick={handleClose}
            className="p-1 rounded hover:bg-gray-100 dark:hover:bg-gray-800"
            data-testid="close-button"
          >
            <X className="w-5 h-5 text-gray-500" />
          </button>
        </div>

        {/* Form */}
        <div className="space-y-4">
          {/* Description field */}
          <div>
            <label
              htmlFor="bug-description"
              className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
            >
              バグの説明 <span className="text-red-500">*</span>
            </label>
            <textarea
              id="bug-description"
              value={description}
              onChange={(e) => handleDescriptionChange(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="発生した問題や再現手順を入力してください..."
              rows={5}
              disabled={isCreating}
              className={clsx(
                'w-full px-3 py-2 rounded-md resize-none',
                'bg-gray-50 dark:bg-gray-800',
                'text-gray-900 dark:text-gray-100',
                'border',
                error && !description.trim()
                  ? 'border-red-500 focus:ring-red-500'
                  : 'border-gray-200 dark:border-gray-700 focus:ring-blue-500',
                'placeholder:text-gray-400 dark:placeholder:text-gray-500',
                'focus:outline-none focus:ring-2',
                'disabled:opacity-50'
              )}
              data-testid="bug-description-input"
            />
          </div>

          {/* bug-create-dialog-unification: Worktree mode switch (Task 6.1 - GitBranch icon added) */}
          <div
            className="flex items-center justify-between p-3 rounded-md bg-gray-50 dark:bg-gray-800"
            data-testid="worktree-switch-container"
          >
            <div className="flex items-center gap-2">
              <GitBranch
                className={clsx(
                  'w-4 h-4',
                  useWorktree ? 'text-violet-500' : 'text-gray-400'
                )}
                data-testid="worktree-switch-git-branch-icon"
              />
              <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                Worktreeモードで作成
              </span>
            </div>
            <button
              type="button"
              role="switch"
              aria-checked={useWorktree}
              data-testid="worktree-mode-switch"
              onClick={() => setUseWorktree(!useWorktree)}
              disabled={isCreating}
              className={clsx(
                'relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full',
                'border-2 border-transparent transition-colors duration-200 ease-in-out',
                'focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-offset-2',
                'disabled:opacity-50 disabled:cursor-not-allowed',
                useWorktree ? 'bg-violet-500' : 'bg-gray-200 dark:bg-gray-600'
              )}
            >
              <span
                className={clsx(
                  'pointer-events-none inline-block h-5 w-5 rounded-full',
                  'bg-white shadow transform ring-0 transition duration-200 ease-in-out',
                  useWorktree ? 'translate-x-5' : 'translate-x-0'
                )}
              />
            </button>
          </div>

          {/* Worktreeモードの説明 */}
          {useWorktree && (
            <p className="text-xs text-violet-600 dark:text-violet-400">
              ブランチとWorktreeを作成し、分離された環境で開発を行います。mainブランチで実行する必要があります。
            </p>
          )}

          {/* Error message */}
          {error && (
            <div className="flex items-center gap-2 p-3 bg-red-50 dark:bg-red-900/20 rounded-md" data-testid="error-message">
              <AlertCircle className="w-4 h-4 text-red-500 shrink-0" />
              <p className="text-sm text-red-600 dark:text-red-400">
                {error}
              </p>
            </div>
          )}
        </div>

        {/* Actions */}
        <div className="flex justify-end gap-3 mt-6">
          <button
            onClick={handleClose}
            disabled={isCreating}
            className={clsx(
              'px-4 py-2 rounded-md',
              'text-gray-700 dark:text-gray-300',
              'hover:bg-gray-100 dark:hover:bg-gray-800',
              'disabled:opacity-50'
            )}
            data-testid="cancel-button"
          >
            キャンセル
          </button>
          <button
            onClick={handleCreate}
            disabled={isCreating || !isValid}
            className={clsx(
              'flex items-center gap-2 px-4 py-2 rounded-md',
              // bug-create-dialog-unification: Color based on worktree mode
              useWorktree
                ? 'bg-violet-500 hover:bg-violet-600 text-white'
                : 'bg-blue-500 hover:bg-blue-600 text-white',
              'disabled:opacity-50 disabled:cursor-not-allowed'
            )}
            data-testid="create-button"
          >
            {isCreating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" data-testid="loading-indicator" />
                作成中...
              </>
            ) : (
              <>
                {/* bug-create-dialog-unification: AgentIcon/AgentBranchIcon based on mode */}
                {useWorktree ? (
                  <AgentBranchIcon data-testid="agent-branch-icon" />
                ) : (
                  <AgentIcon data-testid="agent-icon" />
                )}
                作成
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}

export default CreateBugDialog;
