#!/bin/bash
# =============================================================================
# Mock Claude CLI for E2E Testing (Streaming Version)
# =============================================================================
# This script emulates Claude CLI's stream-json output format with PROGRESSIVE
# output for E2E tests that verify streaming log display.
#
# Unlike mock-claude.sh which outputs all at once, this script outputs
# each JSON line with a delay to simulate real streaming behavior.
#
# Usage:
#   E2E_MOCK_CLAUDE_COMMAND=/path/to/mock-claude-streaming.sh
#
# Environment Variables:
#   E2E_MOCK_STREAM_DELAY: Delay between log lines in seconds (default: 0.3)
#
# Supports phases:
#   - /kiro:spec-requirements, /spec-manager:requirements
#   - /kiro:spec-design, /spec-manager:design
#   - /kiro:spec-tasks, /spec-manager:tasks
#   - /kiro:spec-impl, /spec-manager:impl
# =============================================================================

set -e

# Generate a unique session ID
SESSION_ID="mock-stream-$(date +%s)-$$"

# Delay between log lines (configurable via env var)
STREAM_DELAY=${E2E_MOCK_STREAM_DELAY:-0.3}

# Parse arguments to determine the phase
PHASE=""
FEATURE_NAME=""

for arg in "$@"; do
  case "$arg" in
    /kiro:spec-requirements*|/spec-manager:requirements*)
      PHASE="requirements"
      ;;
    /kiro:spec-design*|/spec-manager:design*)
      PHASE="design"
      ;;
    /kiro:spec-tasks*|/spec-manager:tasks*)
      PHASE="tasks"
      ;;
    /kiro:spec-impl*|/spec-manager:impl*)
      PHASE="impl"
      ;;
  esac
done

# Extract feature name from command arguments
CAPTURE_NEXT=false
for arg in "$@"; do
  if $CAPTURE_NEXT; then
    FEATURE_NAME="$arg"
    CAPTURE_NEXT=false
    continue
  fi
  if [[ "$arg" =~ ^/kiro:|^/spec-manager: ]]; then
    if [[ "$arg" =~ \  ]]; then
      FEATURE_NAME=$(echo "$arg" | cut -d' ' -f2-)
    else
      CAPTURE_NEXT=true
    fi
  fi
done

# Default feature name if not found
if [ -z "$FEATURE_NAME" ]; then
  FEATURE_NAME="test-feature"
fi

# Default to unknown if no phase detected
if [ -z "$PHASE" ]; then
  PHASE="unknown"
fi

# =============================================================================
# Helper Functions
# =============================================================================

# Output a JSON line with optional delay
output_line() {
  echo "$1"
  sleep "$STREAM_DELAY"
}

# Get the spec directory path
get_spec_dir() {
  echo "$(pwd)/.kiro/specs/${FEATURE_NAME}"
}

# Update spec.json with new phase status
update_spec_json() {
  local spec_dir="$1"
  local phase="$2"
  local spec_json="${spec_dir}/spec.json"

  if [ ! -f "$spec_json" ]; then
    return
  fi

  python3 - "$spec_json" "$phase" << 'PYTHON_SCRIPT'
import json
import sys
from datetime import datetime

spec_json_path = sys.argv[1]
phase = sys.argv[2]

try:
    with open(spec_json_path, 'r') as f:
        data = json.load(f)

    phase_map = {
        'requirements': 'requirements-generated',
        'design': 'design-generated',
        'tasks': 'tasks-generated',
        'impl': 'implementation-in-progress'
    }

    if phase in phase_map:
        data['phase'] = phase_map[phase]

    if phase in ['requirements', 'design', 'tasks']:
        if 'approvals' not in data:
            data['approvals'] = {}
        if phase not in data['approvals']:
            data['approvals'][phase] = {}
        data['approvals'][phase]['generated'] = True

    data['updated_at'] = datetime.utcnow().isoformat() + 'Z'

    with open(spec_json_path, 'w') as f:
        json.dump(data, f, indent=2)

except Exception as e:
    print(f"Error updating spec.json: {e}", file=sys.stderr)
PYTHON_SCRIPT
}

# Generate artifact files (same as mock-claude.sh)
generate_requirements() {
  local spec_dir="$1"
  local output_file="${spec_dir}/requirements.md"

  cat > "$output_file" << EOF
# Requirements

## Functional Requirements

### 1. Core Feature Requirements

- **REQ-001**: The system shall provide the requested feature functionality
  - Acceptance Criteria: Feature is accessible and functional
  - Priority: High

- **REQ-002**: The system shall handle edge cases gracefully
  - Acceptance Criteria: No crashes on invalid input
  - Priority: Medium

---
_Generated by Mock Claude CLI (Streaming) for E2E Testing_
EOF

  update_spec_json "$spec_dir" "requirements"
}

generate_design() {
  local spec_dir="$1"
  local output_file="${spec_dir}/design.md"

  cat > "$output_file" << EOF
# Technical Design

## Overview

This document describes the technical design for the ${FEATURE_NAME} feature.

## Architecture

### Component Structure

- Component A: Core Logic
- Component B: State Manager
- Component C: Data Layer

---
_Generated by Mock Claude CLI (Streaming) for E2E Testing_
EOF

  update_spec_json "$spec_dir" "design"
}

generate_tasks() {
  local spec_dir="$1"
  local output_file="${spec_dir}/tasks.md"

  cat > "$output_file" << EOF
# Implementation Tasks

## Task 1: Setup Infrastructure

- [ ] 1.1 Create project structure
- [ ] 1.2 Configure build system

## Task 2: Implement Core Components

- [ ] 2.1 Implement Component A
- [ ] 2.2 Implement Component B

---
_Generated by Mock Claude CLI (Streaming) for E2E Testing_
EOF

  update_spec_json "$spec_dir" "tasks"
}

# =============================================================================
# Main Output Generation (Streaming)
# =============================================================================

# Output init message (always first)
output_line '{"type":"system","subtype":"init","session_id":"'"$SESSION_ID"'","tools":[],"mcp_servers":[],"model":"claude-sonnet-4-20250514","cwd":"'"$(pwd)"'"}'

# Phase-specific streaming responses
case "$PHASE" in
  requirements)
    SPEC_DIR=$(get_spec_dir)

    # Simulate step-by-step execution
    output_line '{"type":"assistant","message":{"id":"msg_1","type":"message","role":"assistant","content":[{"type":"text","text":"Analyzing project requirements..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":50,"output_tokens":10}}}'

    output_line '{"type":"assistant","message":{"id":"msg_2","type":"message","role":"assistant","content":[{"type":"text","text":"Generating functional requirements..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":60,"output_tokens":15}}}'

    output_line '{"type":"assistant","message":{"id":"msg_3","type":"message","role":"assistant","content":[{"type":"text","text":"REQ-001: Core feature functionality"}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":70,"output_tokens":20}}}'

    output_line '{"type":"assistant","message":{"id":"msg_4","type":"message","role":"assistant","content":[{"type":"text","text":"REQ-002: Edge case handling"}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":80,"output_tokens":25}}}'

    # Generate file
    if [ -d "$SPEC_DIR" ]; then
      generate_requirements "$SPEC_DIR"
    fi

    output_line '{"type":"assistant","message":{"id":"msg_5","type":"message","role":"assistant","content":[{"type":"text","text":"✅ Requirements generated at .kiro/specs/'"$FEATURE_NAME"'/requirements.md"}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":100,"output_tokens":50}}}'

    output_line '{"type":"result","subtype":"success","duration_ms":3000,"num_turns":5,"total_cost_usd":0.005,"session_id":"'"$SESSION_ID"'"}'
    ;;

  design)
    SPEC_DIR=$(get_spec_dir)

    output_line '{"type":"assistant","message":{"id":"msg_1","type":"message","role":"assistant","content":[{"type":"text","text":"Analyzing requirements..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":50,"output_tokens":10}}}'

    output_line '{"type":"assistant","message":{"id":"msg_2","type":"message","role":"assistant","content":[{"type":"text","text":"Designing component architecture..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":60,"output_tokens":15}}}'

    output_line '{"type":"assistant","message":{"id":"msg_3","type":"message","role":"assistant","content":[{"type":"text","text":"Component A: Core Logic layer"}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":70,"output_tokens":20}}}'

    if [ -d "$SPEC_DIR" ]; then
      generate_design "$SPEC_DIR"
    fi

    output_line '{"type":"assistant","message":{"id":"msg_4","type":"message","role":"assistant","content":[{"type":"text","text":"✅ Design generated at .kiro/specs/'"$FEATURE_NAME"'/design.md"}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":100,"output_tokens":50}}}'

    output_line '{"type":"result","subtype":"success","duration_ms":2500,"num_turns":4,"total_cost_usd":0.004,"session_id":"'"$SESSION_ID"'"}'
    ;;

  tasks)
    SPEC_DIR=$(get_spec_dir)

    output_line '{"type":"assistant","message":{"id":"msg_1","type":"message","role":"assistant","content":[{"type":"text","text":"Analyzing design document..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":50,"output_tokens":10}}}'

    output_line '{"type":"assistant","message":{"id":"msg_2","type":"message","role":"assistant","content":[{"type":"text","text":"Breaking down into tasks..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":60,"output_tokens":15}}}'

    if [ -d "$SPEC_DIR" ]; then
      generate_tasks "$SPEC_DIR"
    fi

    output_line '{"type":"assistant","message":{"id":"msg_3","type":"message","role":"assistant","content":[{"type":"text","text":"✅ Tasks generated at .kiro/specs/'"$FEATURE_NAME"'/tasks.md"}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":100,"output_tokens":50}}}'

    output_line '{"type":"result","subtype":"success","duration_ms":2000,"num_turns":3,"total_cost_usd":0.003,"session_id":"'"$SESSION_ID"'"}'
    ;;

  impl)
    output_line '{"type":"assistant","message":{"id":"msg_1","type":"message","role":"assistant","content":[{"type":"text","text":"Reading tasks.md..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":50,"output_tokens":10}}}'

    output_line '{"type":"assistant","message":{"id":"msg_2","type":"message","role":"assistant","content":[{"type":"text","text":"Starting implementation..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":60,"output_tokens":15}}}'

    output_line '{"type":"assistant","message":{"id":"msg_3","type":"message","role":"assistant","content":[{"type":"tool_use","id":"tool_1","name":"Write","input":{"file_path":"src/feature.ts","content":"// Implementation code"}}],"model":"claude-sonnet-4-20250514","stop_reason":"tool_use","usage":{"input_tokens":70,"output_tokens":100}}}'

    output_line '{"type":"user","message":{"role":"user","content":[{"type":"tool_result","tool_use_id":"tool_1","content":"File written successfully"}]}}'

    output_line '{"type":"assistant","message":{"id":"msg_4","type":"message","role":"assistant","content":[{"type":"text","text":"✅ Implementation complete"}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":150,"output_tokens":50}}}'

    output_line '{"type":"result","subtype":"success","duration_ms":5000,"num_turns":5,"total_cost_usd":0.01,"session_id":"'"$SESSION_ID"'"}'
    ;;

  *)
    output_line '{"type":"assistant","message":{"id":"msg_mock","type":"message","role":"assistant","content":[{"type":"text","text":"Processing unknown phase..."}],"model":"claude-sonnet-4-20250514","stop_reason":"end_turn","usage":{"input_tokens":10,"output_tokens":10}}}'
    output_line '{"type":"result","subtype":"success","duration_ms":500,"num_turns":1,"total_cost_usd":0.0001,"session_id":"'"$SESSION_ID"'"}'
    ;;
esac

exit 0
