/**
 * Event Log Types
 * Requirements: 4.1, 4.2, 4.3
 *
 * Defines the event log data structures for Spec-level activity logging.
 * Uses discriminated union pattern for type-safe event handling.
 */

// =============================================================================
// Event Type
// =============================================================================

/**
 * Event type enumeration
 * Requirements: 4.3
 */
export type EventType =
  | 'agent:start'
  | 'agent:complete'
  | 'agent:fail'
  | 'auto-execution:start'
  | 'auto-execution:complete'
  | 'auto-execution:fail'
  | 'auto-execution:stop'
  | 'approval:update'
  | 'worktree:create'
  | 'worktree:merge'
  | 'worktree:delete'
  | 'phase:transition'
  | 'review:start'
  | 'review:complete'
  | 'inspection:start'
  | 'inspection:complete';

// =============================================================================
// Base Event Log Entry
// =============================================================================

/**
 * Base event log entry structure
 * Requirements: 4.1
 */
export interface EventLogEntryBase {
  /** ISO 8601 format UTC timestamp */
  readonly timestamp: string;
  /** Event type */
  readonly type: EventType;
  /** Human-readable description */
  readonly message: string;
}

// =============================================================================
// Event-specific Data Types
// =============================================================================

/**
 * Agent-related event data
 * Requirements: 4.2
 */
export interface AgentEventData {
  /** Agent identifier */
  readonly agentId: string;
  /** Workflow phase */
  readonly phase: string;
  /** Command executed */
  readonly command?: string;
  /** Process exit code */
  readonly exitCode?: number;
  /** Error message if failed */
  readonly errorMessage?: string;
}

/**
 * Auto-execution event data
 * Requirements: 4.2
 */
export interface AutoExecutionEventData {
  /** Execution status */
  readonly status: 'started' | 'completed' | 'failed' | 'stopped';
  /** Starting phase */
  readonly startPhase?: string;
  /** Ending phase */
  readonly endPhase?: string;
  /** Error message if failed */
  readonly errorMessage?: string;
}

/**
 * Approval event data
 * Requirements: 4.2
 */
export interface ApprovalEventData {
  /** Phase being approved */
  readonly phase: 'requirements' | 'design' | 'tasks';
  /** Whether approved (true) or unapproved (false) */
  readonly approved: boolean;
}

/**
 * Worktree event data
 * Requirements: 4.2
 */
export interface WorktreeEventData {
  /** Worktree path */
  readonly worktreePath?: string;
  /** Git branch name */
  readonly branch?: string;
  /** Spec commit status (untracked, committed-clean, committed-dirty) */
  readonly specStatus?: string;
  /** List of files copied during conversion (for untracked specs) */
  readonly copiedFiles?: string[];
  /** Additional metadata or notes */
  readonly notes?: string;
}

/**
 * Phase transition event data
 * Requirements: 4.2
 */
export interface PhaseTransitionEventData {
  /** Previous phase */
  readonly oldPhase: string;
  /** New phase */
  readonly newPhase: string;
}

/**
 * Review/Inspection event data
 * Requirements: 4.2
 */
export interface ReviewEventData {
  /** Round number */
  readonly roundNumber?: number;
  /** Result of the review */
  readonly result?: 'go' | 'stop' | 'pending';
}

// =============================================================================
// Discriminated Union Event Log Entry
// =============================================================================

/**
 * Complete EventLogEntry type using discriminated union
 * Requirements: 4.1, 4.2, 4.3
 *
 * This allows type-safe handling of different event types with their
 * specific data fields.
 */
export type EventLogEntry =
  | (EventLogEntryBase & { type: 'agent:start' | 'agent:complete' | 'agent:fail' } & AgentEventData)
  | (EventLogEntryBase & { type: 'auto-execution:start' | 'auto-execution:complete' | 'auto-execution:fail' | 'auto-execution:stop' } & AutoExecutionEventData)
  | (EventLogEntryBase & { type: 'approval:update' } & ApprovalEventData)
  | (EventLogEntryBase & { type: 'worktree:create' | 'worktree:merge' | 'worktree:delete' } & WorktreeEventData)
  | (EventLogEntryBase & { type: 'phase:transition' } & PhaseTransitionEventData)
  | (EventLogEntryBase & { type: 'review:start' | 'review:complete' | 'inspection:start' | 'inspection:complete' } & ReviewEventData);

// =============================================================================
// Event Log Input (for creating events - timestamp auto-generated)
// =============================================================================

/**
 * Base input type (no timestamp)
 */
interface EventLogInputBase {
  /** Event type */
  readonly type: EventType;
  /** Human-readable description */
  readonly message: string;
}

/**
 * Event log input type (timestamp is auto-generated by the service)
 * Requirements: 4.1
 *
 * This is a distributive type that properly handles the union.
 */
export type EventLogInput =
  | (EventLogInputBase & { type: 'agent:start' | 'agent:complete' | 'agent:fail' } & AgentEventData)
  | (EventLogInputBase & { type: 'auto-execution:start' | 'auto-execution:complete' | 'auto-execution:fail' | 'auto-execution:stop' } & AutoExecutionEventData)
  | (EventLogInputBase & { type: 'approval:update' } & ApprovalEventData)
  | (EventLogInputBase & { type: 'worktree:create' | 'worktree:merge' | 'worktree:delete' } & WorktreeEventData)
  | (EventLogInputBase & { type: 'phase:transition' } & PhaseTransitionEventData)
  | (EventLogInputBase & { type: 'review:start' | 'review:complete' | 'inspection:start' | 'inspection:complete' } & ReviewEventData);

// =============================================================================
// Error Types
// =============================================================================

/**
 * Event log error types
 * Requirements: design.md Data Contracts & Integration
 */
export type EventLogError =
  | { type: 'NOT_FOUND'; specId: string }
  | { type: 'PARSE_ERROR'; line: number; message: string }
  | { type: 'IO_ERROR'; message: string };
